header_paths = [
    'src/Base64',
    'src/Cryptography',
    'src/ImageResources/FBDialog',
    'src/ImageResources/FBFriendPickerView',
    'src/ImageResources/FBLoginView',
    'src/ImageResources/FBPlacePickerView',
    'src/ImageResources/FBProfilePictureView',
    'src/JSON'
]

defines = {
    
}

flags = [
	'-Wno-trigraphs',
	'-Wno-missing-field-initializers',
	'-Wno-missing-prototypes',
	'-Wreturn-type',
	'-Wno-implicit-atomic-properties',
	'-Wno-receiver-is-weak',
	'-Wformat',
	'-Wno-missing-braces',
	'-Wparentheses',
	'-Wswitch',
	'-Wno-unused-function',
	'-Wno-unused-label',
	'-Wno-unused-parameter',
	'-Wunused-variable',
	'-Wunused-value',
	'-Wno-uninitialized',
	'-Wno-unknown-pragmas',
	'-Wno-shadow',
	'-Wno-four-char-constants',
	'-Wno-conversion',
	'-Wno-sign-compare',
	'-Wno-shorten-64-to-32',
	'-Wpointer-sign',
	'-Wno-newline-eof',
	'-Wno-selector',
	'-Wno-strict-selector-match',
	'-Wno-undeclared-selector',
	'-Wno-deprecated-implementations',
	'-Wprotocol',
	'-Wdeprecated-declarations',
	'-Wno-sign-conversion',
]

deps = [
    'UIKit',
    'Accounts',
    'sqlite',
    'CoreLocation',
    'Social',
    'AdSupport',
]

sources = [
        'src/Base64/FBBase64.m',
        'src/Cryptography/FBCrypto.m',
        'src/Facebook.m',
        'src/FBAccessTokenData.m',
        'src/FBAppBridge.m',
        'src/FBAppBridgeTypeToJSONConverter.m',
        'src/FBAppCall.m',
        'src/FBAppEvents.m',
        'src/FBAppLinkData.m',
        'src/FBCacheDescriptor.m',
        'src/FBCacheIndex.m',
        'src/FBDataDiskCache.m',
        'src/FBDialog.m',
        'src/FBDialogs.m',
        'src/FBDialogsData.m',
        'src/FBDialogsParams.m',
        'src/FBDynamicFrameworkLoader.m',
        'src/FBError.m',
        'src/FBErrorUtility.m',
        'src/FBFetchedAppSettings.m',
        'src/FBFrictionlessRecipientCache.m',
        'src/FBFrictionlessRequestSettings.m',
        'src/FBFriendPickerCacheDescriptor.m',
        'src/FBFriendPickerViewController.m',
        'src/FBGraphObject.m',
        'src/FBGraphObjectPagingLoader.m',
        'src/FBGraphObjectTableCell.m',
        'src/FBGraphObjectTableDataSource.m',
        'src/FBGraphObjectTableSelection.m',
        'src/FBImageResourceLoader.m',
        'src/FBInsights.m',
        'src/FBLogger.m',
        'src/FBLoginDialog.m',
        'src/FBLoginDialogParams.m',
        'src/FBLoginView.m',
        'src/FBNativeDialogs.m',
        'src/FBOpenGraphActionShareDialogParams.m',
        'src/FBPlacePickerCacheDescriptor.m',
        'src/FBPlacePickerViewController.m',
        'src/FBProfilePictureView.m',
        'src/FBRequest.m',
        'src/FBRequestBody.m',
        'src/FBRequestConnection.m',
        'src/FBRequestConnectionRetryManager.m',
        'src/FBRequestHandlerFactory.m',
        'src/FBRequestMetadata.m',
        'src/FBSession.m',
        'src/FBSessionAppEventsState.m',
        'src/FBSessionAppSwitchingLoginStategy.m',
        'src/FBSessionAuthLogger.m',
        'src/FBSessionFacebookAppNativeLoginStategy.m',
        'src/FBSessionFacebookAppWebLoginStategy.m',
        'src/FBSessionInlineWebViewLoginStategy.m',
        'src/FBSessionLoginStrategyParams.m',
        'src/FBSessionManualTokenCachingStrategy.m',
        'src/FBSessionSafariLoginStategy.m',
        'src/FBSessionSystemLoginStategy.m',
        'src/FBSessionTokenCachingStrategy.m',
        'src/FBSessionUtility.m',
        'src/FBSettings.m',
        'src/FBShareDialogParams.m',
        'src/FBSystemAccountStoreAdapter.m',
        'src/FBTask.m',
        'src/FBTaskCompletionSource.m',
        'src/FBTestSession.m',
        'src/FBURLConnection.m',
        'src/FBUserSettingsViewController.m',
        'src/FBUtility.m',
        'src/FBViewController.m',
        'src/FBWebDialogs.m',
        'src/ImageResources/FBDialog/FBDialogClosePNG.m',
        'src/ImageResources/FBFriendPickerView/FBFriendPickerViewDefaultPNG.m',
        'src/ImageResources/FBLoginView/FBLoginViewButtonPNG.m',
        'src/ImageResources/FBLoginView/FBLoginViewButtonPressedPNG.m',
        'src/ImageResources/FBPlacePickerView/FBPlacePickerViewGenericPlacePNG.m',
        'src/ImageResources/FBProfilePictureView/FBProfilePictureViewBlankProfilePortraitPNG.m',
        'src/ImageResources/FBProfilePictureView/FBProfilePictureViewBlankProfileSquarePNG.m',
        'src/NSError+FBError.m',
]

Import('env')
env.BuildLibrary('FacebookSDK', sources, header_paths=header_paths, static=True, flags = flags, defines = defines, deps = deps)




